Dev
kymatio/murenn pull request #36
Opened 2024-03-25 14:26 UTC by xir4n

2024-03-25 14:37 UTC, lostanlen requested changes
thank you! good luck with future edits 🍀

2024-03-25 14:37 UTC, lostanlen commented on murenn/__init__.py
> +from .dtcwt.graph import MURENN_GRAPH
`from .dtcwt.murenn import MuReNNDirect`

2024-03-25 14:37 UTC, lostanlen commented on murenn/dtcwt/graph.py
> +class MURENN_GRAPH(torch.nn.Module):
`class MuReNNDirect`

2024-03-25 14:37 UTC, lostanlen commented on murenn/dtcwt/graph.py
> +        J=8,
no default values for keyword arguments `J`, `T`, `Q`

use required keyword arguments
`def __init__(self, *, J, Q, T, in_channels, padding_mode='symmetric')`

2024-03-25 14:37 UTC, lostanlen commented on murenn/dtcwt/graph.py
> +        self.padding_mode = padding_mode
no need to store padding mode and J twice. it's already in DTCWT ?

2024-03-25 14:37 UTC, lostanlen commented on murenn/dtcwt/graph.py
> +
initialize `Conv1D` and downsampling operators here, not in forward

2024-03-25 14:37 UTC, lostanlen commented on murenn/dtcwt/graph.py
> +            down = murenn.DTCWT(
move to `__init__`

2024-03-25 14:37 UTC, lostanlen commented on murenn/dtcwt/graph.py
> +            conv1d = torch.nn.Conv1d(
move to `__init__`

2024-03-25 14:37 UTC, lostanlen commented on murenn/dtcwt/graph.py
> +        C = bps[0].shape[1]
should be a keyword argument `in_channels`

2024-03-25 14:37 UTC, lostanlen commented on murenn/dtcwt/graph.py
> +            y_j, _ = down(conv1d(torch.abs(bps[j])))#B*(C*Q)*N
should be three or four lines

2024-03-25 14:37 UTC, lostanlen commented on murenn/dtcwt/graph.py
> +        ys = torch.stack(ys, dim=2) #B*(C*Q)*J*N
`# B * C * Q * J * N_J`

or

`# B * C * J * Q * N_J`

2024-03-25 14:37 UTC, lostanlen commented on tests/test_graph.py
> +    assert y.shape == (B, C*Q, J, 2**4)
update shape

2024-03-25 14:37 UTC, lostanlen commented on tests/test_graph.py
> +    assert y.shape == (B, C*Q, J, 2**4)
test differentiability: require grad in the weights of the Conv1D's
define a loss function based on the output of MuReNNDirect. For example: the sum of all coefficients
Compute `w.grad`
It should be float32, not `None`

2024-03-26 15:02 UTC, lostanlen approved these changes
Excellent work. I only have one remark about the name of the module. `graph.py` does not seem ideal. Maybe `nn.py` ? This wait it mirror `torch.nn`

2024-03-26 15:22 UTC, xir4n commented on murenn/__init__.py
> +from .dtcwt.graph import MuReNNDirect
ok!

2024-03-26 15:39 UTC, lostanlen approved these changes
Thank you!

2024-03-26 15:45 UTC, lostanlen commented
```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 5ccb288774fdfb07a7e7025ffec286971c06d8d7b4fb162525334616d7629ff9
             Got        d7ab2fa6f65c39cf3ad9138fec65d692f8825a96b349446293db537c5a246c6a
```

python 3.11

2024-03-26 16:07 UTC, lostanlen commented
>  I don't know what happened, but after rerunning the workflow, the error disappeared...?

Indeed. Sounds like the problem was unrelated with murenn code and had to do with checksums in the package management system. Regardless, this looks good! Thanks again!

2024-03-26 16:07 UTC, merged